site_name: Ranged Heap

repo_url: https://github.com/giuseppeambrosio97/ranged-heap
edit_uri: edit/main/docs

theme:
  name: material
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: cyan
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: cyan
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Open Sans
    code: Fira Code
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: google
  - include-markdown

nav:
  - RangedHeap:
    - Home Page: index.md
    - API Reference: api/ranged_heap_all.md
  - Getting Started:
      - Introduction: getting_started/introduction.md
      - Installation: getting_started/installation.md
      - Quickstart: getting_started/quickstart.md
  - User Guide:
      - Introduction: user_guide/introduction.md
      - Greedy Algorithms: user_guide/greedy_algorithms.md
      - API Reference: api/ranged_heap_all.md
  - API Reference:
      - RangedHeap: api/ranged_heap.md
      - errors: api/errors.md
      - bisectw: api/bisectw.md
  - Development:
      - Roadmap: development/roadmap.md
      - Contributing: development/contributing.md
      - Code of Conduct: development/code_of_conduct.md
      - Changelog: development/changelog.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets:
      restrict_base_path: false
  - admonition
  - tables
  - toc:
      permalink: "#"
  - attr_list


extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-RP4PM5PGLN
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/giuseppeambrosio97/ranged-heap
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/giuseppe-ambrosio-762263182
  chatbot:
    url: https://2prxfnwkygf4vexczrbpcq.streamlit.app/?embed=true

watch:
  - ranged_heap