name: 'Setup and Install'
description: 'Setup Python, install Poetry, and install dependencies'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.9'
  dependencies:
    description: 'Dependencies to install with Poetry'
    required: true
    default: '--with dev'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      run: pip install poetry
      shell: bash

    - name: Install dependencies
      working-directory: ./src/ranged_heap
      run: poetry install ${{ inputs.dependencies }}
      shell: bash
