name: RangedHeap CI CD

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  lint: 
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: ['3.9', '3.10', '3.11']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup and Install
        uses: ./.github/actions/setup-and-install
        with:
          python-version: ${{ matrix.python }}
          dependencies: '--with dev'

      - name: Ruff check
        working-directory: ./src/ranged_heap
        run: poetry run ruff check

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: ['3.9', '3.10', '3.11']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup and Install
        uses: ./.github/actions/setup-and-install
        with:
          python-version: ${{ matrix.python }}
          dependencies: '--with test'

      - name: Run tests
        working-directory: ./src/ranged_heap
        run: poetry run pytest
