name: RangedHeap CI CD

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python: ['3.9']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup and Install
        uses: ./.github/actions/setup-and-install
        with:
          python-version: ${{ matrix.python }}
          dependencies: '--only dev'

      - name: Ruff check
        working-directory: ./src/ranged_heap
        run: poetry run ruff check
        shell: bash

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python: ['3.9']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup and Install
        uses: ./.github/actions/setup-and-install
        with:
          python-version: ${{ matrix.python }}
          dependencies: '--only test'

      - name: Run tests
        working-directory: ./src/ranged_heap
        run: poetry run pytest
        shell: bash

  doc:
    if: github.ref == 'refs/heads/main'
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup and Install
        uses: ./.github/actions/setup-and-install
        with:
          python-version: "3.9"
          dependencies: '--only doc'

      - name: Build documentation
        working-directory: ./src/ranged_heap
        run: poetry run mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/ranged_heap/site

  tag:
    if: github.ref == 'refs/heads/main'
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup and Install
        uses: ./.github/actions/setup-and-install

      - name: Create git tag
        working-directory: ./src/ranged_heap
        id: get_version
        run: |
          echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV
          echo "Version set to $(poetry version -s)"
          echo "Version from GITHUB_ENV: $VERSION"

      - name: Push tag
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}
